.TH NIP4 1 "Oct 4 2025"
.SH NAME
nip4 \- image processing spreadsheet

.SH SYNOPSIS
.B nip4
.RI [ filename1.. ]

.SH DESCRIPTION
.B nip4
is a spreadsheet-like tool for scientific image processing. You can develop
large image processing pipelines interactively, then execute them batch-style
with the separate
.B nip4-batch(1)
program. It is fast and uses relatively little memory.

A full manual is available online.

.SH EXAMPLES

.TP
.B nip4 fred.jpg
Start nip4, loading the image fred.jpg.

.TP
.B nip4 sample.ws
Start nip4, loading a previous saved workspace.

.SH SEE ALSO
nip4-batch(1)

.SH COPYRIGHT
2025 (c) libvips.org
